import { Cloud, Sun, Droplets, Wind, Shield, Apple, Activity, Moon } from 'lucide-react';
import {
  canhKhoQuaXuongSenImage,
  cheVangMatGanImage,
  ngamChanNgaiCuuImage,
  nuocDauDenRangImage,
  nuocGungNgheMatOngImage,
  nuocTiaToDuongPheImage,
  siroLaLotMatOngImage,
  toiNgamMatOngImage,
  traAtisoDoHatChiaImage,
  traLaSenMatOngImage,
  xongHoiTinhDauBacHaImage,
  nhaDamDuongPhenImage,
  nuocRauMaImage,
  traGungDuongDenImage,
  chaoTiaToImage,
  nuocSaChanhImage,
  traTamSenImage,
  nuocVoiTuoiImage,
  traGungMatOngImage,
  nuocDauVanRangImage,
  traHoaCucImage,
} from './remedyImages';

export const environmentData = [
  { icon: Cloud, title: 'Chất lượng không khí (AQI)', value: 75, status: 'moderate' as const, description: 'Chất lượng không khí ở mức trung bình. Nhạy cảm nên hạn chế ra ngoài lâu.' },
  { icon: Sun, title: 'Chỉ số UV', value: 8, status: 'unhealthy' as const, description: 'Tia UV cao. Thoa kem chống nắng SPF50+ và đeo kính khi ra ngoài.' },
  { icon: Droplets, title: 'Độ ẩm không khí', value: '65%', status: 'good' as const, description: 'Độ ẩm lý tưởng, thoải mái cho hô hấp và làn da của bạn.' },
  { icon: Wind, title: 'Chất lượng gió', value: 'Tốt', status: 'good' as const, description: 'Gió nhẹ từ biển, không khí lưu thông tốt — lý tưởng cho đi dạo sáng sớm.' },
];

export const healthAdvices = [
  { icon: Shield, title: 'Bảo vệ sức khỏe', category: 'protection' as const,
    modernAdvice: ['Đeo khẩu trang N95 khi AQI > 70', 'Kem chống nắng SPF 50+, đeo kính UV', 'Tránh hoạt động ngoài trời 10h–15h'],
    traditionalAdvice: ['Uống nước lá sen thanh nhiệt, giải độc', 'Tắm nước lá tía tô làm dịu da', 'Xông hơi tinh dầu bạc hà làm sạch phổi'] },
  { icon: Apple, title: 'Dinh dưỡng', category: 'nutrition' as const,
    modernAdvice: ['Bổ sung vitamin C, E tăng miễn dịch', 'Uống 2–2.5L nước mỗi ngày', 'Rau xanh, trái cây giàu chống oxi hóa'],
    traditionalAdvice: ['Chè hoa nhài giải độc gan', 'Canh khổ qua xương mát gan', 'Siro lá lốt mật ong tăng đề kháng'] },
  { icon: Activity, title: 'Vận động', category: 'exercise' as const,
    modernAdvice: ['Tập trong phòng có lọc không khí', 'Yoga, thiền cải thiện hô hấp', 'Đi bộ sáng sớm hoặc chiều muộn'],
    traditionalAdvice: ['Khí công buổi sớm hít thở khí lành', 'Võ cổ truyền rèn luyện toàn thân', 'Đi chân trần trên cỏ tiếp đất'] },
  { icon: Moon, title: 'Nghỉ ngơi', category: 'rest' as const,
    modernAdvice: ['Ngủ đủ 7–8 tiếng mỗi đêm', 'Máy lọc không khí trong phòng ngủ', 'Ngắt điện tử trước ngủ 1 tiếng'],
    traditionalAdvice: ['Ngâm chân nước ấm + muối trước ngủ', 'Trà hoa cúc hay hoa nhài giúp dễ ngủ', 'Gối thơm thảo mộc oải hương, bạc hà'] },
];

export const traditionalRemedies = [
  { id: 'tra-la-sen', name: 'Trà Lá Sen Mật Ong', category: 'Thanh nhiệt', ingredients: ['Lá sen tươi', 'Mật ong', 'Chanh'],
    benefits: 'Thanh nhiệt, giải độc gan, giúp cơ thể chống lại tác hại của ô nhiễm không khí.',
    keywords: ['nóng trong người', 'nổi mụn', 'khát nước', 'giải độc', 'thanh nhiệt', 'mát gan'],
    usage: 'Uống 2–3 lần/ngày, tốt nhất vào sáng sớm và chiều muộn.', image: '🍵',
    steps: ['Rửa sạch lá sen tươi, thái nhỏ hoặc vò nát nhẹ.', 'Hãm lá sen với 500ml nước sôi trong 10-15 phút.', 'Chờ nước nguội bớt (khoảng 40°C), thêm 2 thìa mật ong và một lát chanh.', 'Khuấy đều và thưởng thức ấm hoặc thêm đá.'],
    imageUrl: traLaSenMatOngImage },
  { id: 'siro-la-lot', name: 'Siro Lá Lốt Mật Ong', category: 'Hô hấp', ingredients: ['Lá lốt', 'Đường phèn', 'Gừng', 'Mật ong'],
    benefits: 'Tăng cường đề kháng, làm sạch đường hô hấp, chống viêm — đặc trị ho khan do bụi mịn.',
    keywords: ['ho', 'ho khan', 'viêm họng', 'đau họng', 'sổ mũi', 'nghẹt mũi', 'bụi mịn'],
    usage: 'Một thìa nhỏ sau bữa ăn, 2–3 lần/ngày. Trẻ em dùng nửa liều.', image: '🌿',
    steps: ['Rửa sạch lá lốt, ngâm nước muối loãng rồi thái chỉ.', 'Gừng cạo vỏ, rửa sạch và thái lát mỏng.', 'Cho lá lốt, gừng và 2 thìa đường phèn vào bát sứ.', 'Hấp cách thủy khoảng 20 phút. Khi lấy ra, chắt lấy nước cốt hòa thêm 1 thìa mật ong.'],
    imageUrl: siroLaLotMatOngImage },
  { id: 'canh-kho-qua', name: 'Canh Khổ Qua Xương Sen', category: 'Tiêu hóa', ingredients: ['Khổ qua', 'Xương ống', 'Hạt sen', 'Gừng'],
    benefits: 'Mát gan, thanh nhiệt, giải độc — phù hợp cho những ngày nắng nóng và AQI cao.',
    keywords: ['nóng gan', 'mụn nhọt', 'tiêu hóa kém', 'ăn không tiêu', 'mát gan'],
    usage: 'Ăn 2–3 lần/tuần vào bữa trưa hoặc tối cùng cơm gạo lứt.', image: '🥣',
    steps: ['Xương ống chần qua nước sôi để khử mùi hôi, rửa sạch.', 'Hầm xương với hạt sen trong 45 phút lấy nước ngọt.', 'Khổ qua bỏ hạt, thái lát mỏng hoặc cắt khúc vừa ăn.', 'Cho khổ qua vào nồi hầm, đun thêm 10 phút, nêm nếm gia vị và vài lát gừng.'],
    imageUrl: canhKhoQuaXuongSenImage },
  { id: 'nuoc-gung', name: 'Nước Gừng Nghệ Mật Ong', category: 'Hô hấp', ingredients: ['Gừng tươi', 'Nghệ tươi', 'Mật ong', 'Chanh'],
    benefits: 'Chống viêm mạnh, tăng cường hệ miễn dịch, bảo vệ dạ dày và đường hô hấp trong mùa giao mùa.',
    keywords: ['đau dạ dày', 'cảm lạnh', 'viêm họng', 'đau họng', 'tăng đề kháng', 'sổ mũi'],
    usage: 'Pha 1 ly nước ấm mỗi sáng khi bụng đói. Uống liên tục 2 tuần.', image: '🫚',
    steps: ['Gừng và nghệ cạo vỏ, rửa sạch, đập dập hoặc giã nát.', 'Cho gừng nghệ vào cốc, chế 300ml nước sôi, đậy nắp hãm 10 phút.', 'Lọc bỏ bã, để nước ấm nguội xuống tầm 40-50°C.', 'Thêm 1-2 thìa mật ong nguyên chất và vài giọt nước cốt chanh, khuấy đều.'],
    imageUrl: nuocGungNgheMatOngImage },
  { id: 'xong-hoi', name: 'Xông Hơi Tinh Dầu Bạc Hà', category: 'Hô hấp', ingredients: ['Lá bạc hà', 'Lá tràm', 'Sả', 'Nước nóng'],
    benefits: 'Thông mũi, giảm nghẹt, diệt khuẩn đường hô hấp — bài thuốc dân gian Quảng Nam phổ biến khi trời trở lạnh.',
    keywords: ['nghẹt mũi', 'cảm cúm', 'nhức đầu', 'viêm xoang', 'khó thở'],
    usage: 'Xông 5–10 phút trước khi ngủ, trùm khăn kín đầu. Không xông quá lâu.', image: '🫧',
    steps: ['Rửa sạch lá bạc hà, lá tràm và sả đập dập.', 'Đun sôi một nồi nước khoảng 2 lít.', 'Cho tất cả lá thảo mộc vào nồi, đun sôi thêm 2 phút rồi tắt bếp.', 'Đặt nồi ở nơi an toàn, trùm chăn kín qua đầu và hé vung từ từ để xông trong 5-10 phút.'],
    imageUrl: xongHoiTinhDauBacHaImage },
  { id: 'tra-hoa-cuc', name: 'Trà Hoa Cúc La Mã', category: 'An thần', ingredients: ['Hoa cúc khô', 'Mật ong', 'Kỷ tử'],
    benefits: 'An thần, giảm stress, cải thiện chất lượng giấc ngủ. Rất tốt cho người thường xuyên mất ngủ do ô nhiễm tiếng ồn đô thị.',
    keywords: ['mất ngủ', 'căng thẳng', 'stress', 'nhức đầu', 'khó ngủ', 'an thần'],
    usage: 'Hãm 3–5 phút với nước 80°C, uống trước khi ngủ 30 phút.', image: '🌼',
    steps: ['Tráng ấm pha trà và hoa cúc sơ qua bằng một ít nước sôi để loại bỏ bụi bẩn.', 'Cho hoa cúc và kỷ tử vào ấm, đổ 200ml nước sôi (khoảng 80-90°C).', 'Hãm trà trong 3-5 phút cho dưỡng chất tiết ra.', 'Thêm mật ong tùy khẩu vị, uống ấm trước khi đi ngủ.'],
    imageUrl: traHoaCucImage },
  { id: 'tra-atiso', name: 'Trà Atiso Đỏ Hạt Chia', category: 'Giải độc', ingredients: ['Hoa atiso đỏ', 'Hạt chia', 'Đường phèn'],
    benefits: 'Hỗ trợ giải độc gan, lọc máu, làm mát cơ thể cực kỳ hiệu quả trong những ngày nắng gắt.',
    keywords: ['giải độc', 'mát gan', 'nóng trong', 'giải khát'],
    usage: 'Uống lạnh vào giữa trưa hoặc đầu giờ chiều.', image: '🌺',
    steps: ['Rửa sạch đài hoa atiso đỏ.', 'Đun sôi hoa atiso với 500ml nước trong 5 phút đến khi nước chuyển màu đỏ thẫm.', 'Vớt bỏ bã hoa, thêm đường phèn khuấy tan.', 'Ngâm hạt chia trong nước lọc 10 phút cho nở, rồi pha chung với nước atiso. Thêm đá khi uống.'],
    imageUrl: traAtisoDoHatChiaImage },
  { id: 'ngam-chan-ngai-cuu', name: 'Nước Ngâm Chân Ngải Cứu', category: 'Xương khớp', ingredients: ['Ngải cứu tươi', 'Muối hạt', 'Gừng già'],
    benefits: 'Lưu thông khí huyết, giảm đau nhức xương khớp do thời tiết thay đổi, giúp ngủ sâu giấc.',
    keywords: ['đau nhức', 'nhức mỏi', 'xương khớp', 'mất ngủ', 'lạnh chân'],
    usage: 'Ngâm chân nước ấm 15 phút mỗi tối trước khi đi ngủ.', image: '🦶',
    steps: ['Ngải cứu rửa sạch, gừng già đập dập nguyên vỏ.', 'Đun sôi 2 lít nước, thả ngải cứu, gừng và 1 nắm muối hạt vào.', 'Đun riu riu khoảng 10 phút cho ra tinh dầu.', 'Pha thêm nước lạnh để nhiệt độ hạ xuống khoảng 40-45°C rồi ngâm ngập mắt cá chân.'],
    imageUrl: ngamChanNgaiCuuImage },
  { id: 'nuoc-tia-to', name: 'Nước Tía Tô Đường Phèn', category: 'Hô hấp', ingredients: ['Lá tía tô', 'Đường phèn', 'Chanh'],
    benefits: 'Giải cảm, làm ấm cơ thể, trị ho và dị ứng thời tiết nổi mẩn ngứa.',
    keywords: ['cảm mạo', 'dị ứng', 'mẩn ngứa', 'sốt', 'giải cảm'],
    usage: 'Uống nóng khi vừa đi ngoài mưa về hoặc khi bị cảm.', image: '🌱',
    steps: ['Rửa sạch lá tía tô, để ráo nước.', 'Đun sôi 1 lít nước, thả lá tía tô vào đun trong 5 phút.', 'Thêm đường phèn vào khuấy tan rồi tắt bếp.', 'Chắt lấy nước, khi uống thêm một chút nước cốt chanh (nước sẽ chuyển sang màu hồng nhạt rất đẹp).'],
    imageUrl: nuocTiaToDuongPheImage },
  { id: 'che-vang', name: 'Nước Chè Vằng Mát Gan', category: 'Thanh nhiệt', ingredients: ['Lá chè vằng khô'],
    benefits: 'Hạ áp, giảm mỡ máu, thanh nhiệt, rất tốt cho tiêu hóa và phụ nữ sau sinh.',
    keywords: ['cao huyết áp', 'mỡ máu', 'tiêu hóa', 'thanh nhiệt', 'mất ngủ'],
    usage: 'Hãm lấy nước uống thay nước lọc hàng ngày.', image: '🌿',
    steps: ['Lấy khoảng 20-30g lá chè vằng khô, tráng qua nước sôi để làm sạch.', 'Cho lá vào ấm, châm 1.5 - 2 lít nước sôi ngập lá.', 'Đậy kín nắp, hãm trong vòng 15-20 phút.', 'Chắt lấy nước, có thể uống ấm hoặc để nguội thay nước lọc.'],
    imageUrl: cheVangMatGanImage },
  { id: 'toi-ngam-mat-ong', name: 'Tỏi Ngâm Mật Ong', category: 'Hô hấp', ingredients: ['Tỏi tươi', 'Mật ong nguyên chất'],
    benefits: 'Kháng sinh tự nhiên, trị ho suyễn, viêm họng hạt, tăng cường hệ miễn dịch cực mạnh.',
    keywords: ['viêm họng', 'ho suyễn', 'cảm cúm', 'tăng đề kháng'],
    usage: 'Ăn 1 tép tỏi và 1 thìa mật ong vào buổi sáng.', image: '🧄',
    steps: ['Tỏi bóc vỏ, đập dập hoặc thái lát mỏng, để ngoài không khí 10 phút để allicin được kích hoạt.', 'Xếp tỏi vào hũ thủy tinh đã tiệt trùng khô ráo.', 'Đổ mật ong nguyên chất ngập mặt tỏi.', 'Đậy kín nắp, ngâm khoảng 15-20 ngày là có thể sử dụng.'],
    imageUrl: toiNgamMatOngImage },
  { id: 'nuoc-dau-den', name: 'Nước Đậu Đen Rang', category: 'Giải độc', ingredients: ['Đậu đen xanh lòng', 'Muối tinh'],
    benefits: 'Bổ thận, lọc máu, giảm rụng tóc, làm sáng mắt và thanh lọc cơ thể trong môi trường khói bụi.',
    keywords: ['giải độc', 'rụng tóc', 'bổ thận', 'thanh lọc', 'mụn'],
    usage: 'Rang chín, hãm nước uống mỗi ngày.', image: '🫘',
    steps: ['Đậu đen rửa sạch, nhặt hạt lép, để thật ráo nước.', 'Rang đậu trên chảo lửa nhỏ, đảo đều tay cho đến khi đậu có mùi thơm và ruột hơi ngả vàng.', 'Mỗi lần lấy khoảng 50g đậu đen rang hãm với 1 lít nước sôi trong bình giữ nhiệt 30 phút.', 'Thêm một nhúm muối tinh cực nhỏ, uống ấm hoặc để tủ lạnh.'],
    imageUrl: nuocDauDenRangImage },
  { id: 'nha-dam-duong-phen', name: 'Nha Đam Đường Phèn', category: 'Thanh nhiệt', ingredients: ['Nha đam tươi', 'Đường phèn', 'Lá dứa'],
    benefits: 'Thanh nhiệt, làm mát gan, đẹp da, trị mụn nhọt, chống viêm hiệu quả.',
    keywords: ['thanh nhiệt', 'mát gan', 'đẹp da', 'mụn nhọt'],
    usage: 'Nấu chín nha đam với đường phèn và lá dứa, uống lạnh.', image: '🌿',
    steps: ['Nha đam gọt sạch vỏ xanh, lấy phần thịt trắng thái hạt lựu, xả nhiều lần với nước muối loãng cho hết nhớt.', 'Trần sơ nha đam qua nước sôi 1 phút rồi vớt ra ngâm ngay vào tô nước đá.', 'Đun sôi 1 lít nước với lá dứa và đường phèn cho tan.', 'Cho nha đam vào đun sôi bùng lên rồi tắt bếp. Ngon hơn khi uống lạnh.'],
    imageUrl: nhaDamDuongPhenImage },
  { id: 'nuoc-rau-ma', name: 'Nước Rau Má', category: 'Giải độc', ingredients: ['Rau má tươi', 'Đường', 'Nước dừa'],
    benefits: 'Hạ sốt, làm mát cơ thể, trị rôm sảy, hỗ trợ làm lành vết thương và thanh lọc cơ thể.',
    keywords: ['giải độc', 'hạ sốt', 'rôm sảy', 'thanh nhiệt', 'mụn'],
    usage: 'Xay nhuyễn rau má, lọc lấy nước uống hàng ngày.', image: '🍀',
    steps: ['Rau má nhặt bỏ rễ và lá úa, rửa sạch nhiều lần rồi ngâm nước muối loãng 15 phút.', 'Cho rau má vào máy xay sinh tố cùng một ít nước lọc hoặc nước dừa tươi.', 'Xay thật nhuyễn rồi dùng rây lọc bỏ bã, lấy phần nước cốt.', 'Thêm đường tùy khẩu vị, uống lạnh kèm đá đập dập.'],
    imageUrl: nuocRauMaImage },
  { id: 'tra-gung-duong-den', name: 'Trà Gừng Đường Đen', category: 'Làm ấm', ingredients: ['Gừng già', 'Đường đen', 'Táo đỏ'],
    benefits: 'Giữ ấm cơ thể, giải cảm lạnh, giảm đau bụng kinh, kích thích tiêu hóa trong những ngày lạnh.',
    keywords: ['cảm lạnh', 'đau bụng', 'tiêu hóa', 'giữ ấm'],
    usage: 'Hãm gừng tươi và đường đen với nước sôi, uống ấm.', image: '☕',
    steps: ['Gừng già rửa sạch, gọt vỏ rồi thái lát thật mỏng.', 'Táo đỏ cắt lát mỏng, bỏ hạt.', 'Cho gừng, táo đỏ và 2 thìa đường đen vào ly sứ.', 'Rót 200ml nước thật sôi vào ly, đậy nắp hãm 10 phút. Khuấy đều và thưởng thức khi còn nóng.'],
    imageUrl: traGungDuongDenImage },
  { id: 'chao-tia-to', name: 'Cháo Tía Tô Giải Cảm', category: 'Hô hấp', ingredients: ['Lá tía tô', 'Hành hoa', 'Gừng tươi', 'Gạo tẻ'],
    benefits: 'Giải cảm lạnh, toát mồ hôi, hạ sốt, làm nhẹ đầu, tốt cho dạ dày.',
    keywords: ['cảm lạnh', 'cảm mạo', 'sốt', 'đau đầu', 'đau bụng', 'giải cảm'],
    usage: 'Ăn nóng 1-2 bát khi có dấu hiệu cảm lạnh, sau đó đắp chăn cho ra mồ hôi.', image: '🍲',
    steps: ['Nấu cháo gạo tẻ chín nhừ.', 'Rửa sạch tía tô, hành hoa thái nhỏ, gừng xắt chỉ.', 'Múc cháo đang sôi sùng sục ra bát, cho rau gia vị vào trộn đều.', 'Ăn ngay khi còn nóng hổi.'],
    imageUrl: chaoTiaToImage },
  { id: 'nuoc-sa-chanh', name: 'Nước Sả Chanh Gừng', category: 'Hô hấp', ingredients: ['Củ sả', 'Chanh', 'Gừng', 'Mật ong'],
    benefits: 'Tăng cường hệ miễn dịch, làm ấm cơ thể, diệt khuẩn đường hô hấp, hỗ trợ tiêu hóa.',
    keywords: ['đề kháng', 'miễn dịch', 'sát khuẩn', 'đầy bụng', 'cảm cúm', 'đau họng'],
    usage: 'Uống ấm 1 ly/ngày vào buổi sáng hoặc khi thời tiết chuyển lạnh.', image: '🍹',
    steps: ['Sả đập dập vụn, gừng thái lát mỏng.', 'Đun sôi sả và gừng với nước khoảng 10 phút rồi tắt bếp.', 'Để nước ấm khoảng 40°C, vắt nước cốt chanh và thêm mật ong.', 'Khuấy đều và thưởng thức.'],
    imageUrl: nuocSaChanhImage },
  { id: 'tra-tam-sen', name: 'Trà Tâm Sen', category: 'An thần',  ingredients: ['Tâm sen khô'],
    benefits: 'Thanh tâm hỏa, trấn tĩnh an thần, chữa mất ngủ, hồi hộp, nhịp tim nhanh.',
    keywords: ['mất ngủ', 'khó ngủ', 'căng thẳng', 'stress', 'hồi hộp', 'an thần'],
    usage: 'Hãm trà uống vào buổi chiều tối. Không nên uống quá đặc hoặc uống khi bụng đói.', image: '🪷',
    steps: ['Lấy 3-5g tâm sen khô (nên sao vàng hạ thổ trước để giảm tính hàn).', 'Tráng qua bằng nước sôi.', 'Hãm tâm sen với nước sôi trong ấm sành khoảng 10 phút.', 'Rót ra chén nhỏ và thưởng thức chậm rãi.'],
    imageUrl: traTamSenImage },
  { id: 'nuoc-voi-tuoi', name: 'Nước Vối Tươi', category: 'Tiêu hóa', ingredients: ['Lá vối tươi hoặc nụ vối'],
    benefits: 'Kích thích tiêu hóa, thanh nhiệt, giải độc, hỗ trợ ổn định đường huyết.',
    keywords: ['tiêu hóa', 'đầy bụng', 'khát nước', 'giải khát', 'mát gan', 'đường huyết'],
    usage: 'Uống thay nước lọc hàng ngày, nhất là trong mùa hè oi bức.', image: '🍂',
    steps: ['Rửa sạch lá vối tươi, vò nhẹ cho lá hơi nát.', 'Cho vào ấm, đổ nước sôi hãm như hãm trà xanh khoảng 15 phút.', 'Nước vối có màu vàng nhạt, vị hơi chát nhẹ, uống vào thấy ngọt hậu.', 'Có thể uống nóng hoặc thêm đá làm thức uống giải khát.'],
    imageUrl: nuocVoiTuoiImage },
  { id: 'tra-gung-mat-ong', name: 'Trà Gừng Mật Ong', category: 'Hô hấp', ingredients: ['Gừng tươi', 'Mật ong nguyên chất', 'Chanh'],
    benefits: 'Làm ấm cơ thể, dịu cổ họng, giảm ho khan, tăng cường sức đề kháng tức thì.',
    keywords: ['ho', 'đau họng', 'viêm họng', 'cảm lạnh', 'giữ ấm', 'đề kháng'],
    usage: 'Uống nóng vào buổi sáng hoặc khi thấy cổ họng có dấu hiệu đau rát.', image: '🍯',
    steps: ['Gừng cạo vỏ, rửa sạch, thái lát mỏng hoặc giã dập.', 'Hãm gừng với 200ml nước sôi khoảng 10 phút.', 'Khi nước còn ấm (khoảng 40°C), pha thêm 2 thìa mật ong và vài giọt nước cốt chanh.', 'Khuấy đều và uống từng ngụm nhỏ để làm dịu họng.'],
    imageUrl: traGungMatOngImage },
  { id: 'nuoc-dau-van-rang', name: 'Nước Đậu Ván Rang', category: 'Thanh nhiệt', ingredients: ['Hạt đậu ván trắng (Bạch biển đậu)'],
    benefits: 'Thanh nhiệt, giải độc, trị cảm nắng, tiêu chảy, giải nhiệt mùa hè cực kỳ hiệu quả.',
    keywords: ['cảm nắng', 'say nắng', 'tiêu chảy', 'khát nước', 'giải nhiệt', 'mát gan'],
    usage: 'Uống lạnh hoặc nguội thay nước lọc trong những ngày nắng nóng gay gắt.', image: '🫘',
    steps: ['Đậu ván nhặt bỏ hạt lép, rửa sạch, phơi khô.', 'Rang đậu ván trên chảo lửa nhỏ đến khi có mùi thơm và hạt hơi vàng.', 'Mỗi lần lấy khoảng 30-50g đậu đã rang đun với 1 lít nước sôi trong 15 phút.', 'Chắt lấy nước uống trong ngày.'],
    imageUrl: nuocDauVanRangImage },
  { id: 'canh-bi-dao', name: 'Canh Bí Đao Thịt Nạc', category: 'Dinh dưỡng', ingredients: ['Bí đao', 'Thịt heo nạc', 'Hành ngò'],
    benefits: 'Làm mát cơ thể, giải thử (trị nắng nóng), lợi tiểu, giảm phù thũng, bổ sung đạm nhẹ nhàng.',
    keywords: ['nóng trong', 'nhiệt miệng', 'lợi tiểu', 'giảm cân', 'thanh mát', 'dinh dưỡng'],
    usage: 'Ăn kèm trong bữa cơm chính, đặc biệt tốt vào những ngày hè oi bức.', image: '🍲',
    steps: ['Bí đao gọt vỏ, bỏ ruột, thái lát mỏng hoặc miếng vuông vừa ăn.', 'Thịt nạc băm nhỏ, ướp chút gia vị.', 'Đun sôi nước, cho thịt băm vào nấu chín, vớt bọt cho nước trong.', 'Thả bí đao vào đun sôi lại khoảng 2-3 phút cho bí chín tới, thêm hành ngò rồi tắt bếp.'],
    imageUrl: '/images/canh_bi_dao.png' },
  { id: 'nuoc-ep-diep-ca', name: 'Nước Ép Diếp Cá', category: 'Tiêu hóa', ingredients: ['Rau diếp cá tươi', 'Đường hoặc Mật ong'],
    benefits: 'Kháng viêm tự nhiên, làm mát gan, trị mụn nhọt, táo bón và bệnh trĩ rất hiệu quả.',
    keywords: ['táo bón', 'nổi mụn', 'trĩ', 'kháng viêm', 'mát gan', 'nóng trong'],
    usage: 'Uống 1 ly nhỏ sau bữa ăn. Nên uống lạnh để giảm mùi tanh của rau.', image: '🌿',
    steps: ['Diếp cá ngâm nước muối loãng, rửa thật sạch, vớt ra để ráo.', 'Cho diếp cá vào máy xay sinh tố cùng một ít nước lọc, xay thật nhuyễn.', 'Dùng rây lọc bỏ bã, lấy phần nước cốt.', 'Thêm chút đường hoặc mật ong, bỏ đá viên vào và thưởng thức ngay.'],
    imageUrl: '/images/nuoc_ep_diep_ca.jpg' },
  { id: 'che-hat-sen-long-nhan', name: 'Chè Hạt Sen Long Nhãn', category: 'An thần', ingredients: ['Hạt sen tươi', 'Nhãn nhục (Long nhãn)', 'Đường phèn'],
    benefits: 'Bổ tâm tỳ, an thần kinh, giúp ngủ ngon, đẹp da, phục hồi sức khỏe cho người suy nhược.',
    keywords: ['mất ngủ', 'suy nhược', 'kém ăn', 'bồi bổ', 'an thần', 'đẹp da'],
    usage: 'Ăn giải tráng miệng hoặc ăn xế. Ngon hơn khi ướp lạnh.', image: '🍧',
    steps: ['Hạt sen bỏ tâm, luộc sơ để loại bỏ bọt chát, sau đó hầm lửa nhỏ đến khi chín mềm nhưng không nát.', 'Vớt hạt sen ra, nhét từng hạt sen vào trong cùi nhãn nhục.', 'Nước luộc sen lọc sạch, cho đường phèn vào đun tan.', 'Thả nhãn bọc sen vào nồi nước đường, đun sôi nhẹ 5 phút rồi tắt bếp.'],
    imageUrl: '/images/che_hat_sen.webp' },
  { id: 'sua-gao-lut-rang', name: 'Sữa Gạo Lứt Rang', category: 'Dinh dưỡng', ingredients: ['Gạo lứt', 'Sữa tươi không đường', 'Nước lọc'],
    benefits: 'Cung cấp năng lượng sạch, giàu vitamin nhóm B, hỗ trợ tiêu hóa, giảm cholesterol.',
    keywords: ['dinh dưỡng', 'giảm cân', 'tiêu hóa', 'cholesterol', 'bổ sung', 'hồi phục'],
    usage: 'Uống ấm vào buổi sáng hoặc dùng làm bữa phụ trong ngày.', image: '🥛',
    steps: ['Gạo lứt nhặt sạch, không vo, rang trên chảo lửa nhỏ đến khi hạt gạo nổ lách tách và có mùi thơm.', 'Cho gạo đã rang vào nồi đun với nước đến khi hạt gạo chín mềm bung nở.', 'Cho hỗn hợp vào máy xay nhuyễn, sau đó lọc qua rây hoặc vải mùng vắt lấy nước cốt.', 'Đun ấm lại nước cốt, pha thêm sữa tươi (và chút đường tùy khẩu vị) rồi thưởng thức.'],
    imageUrl: '/images/sua_gao_lut.jpg' },
  { id: 'chanh-dao-mat-ong', name: 'Chanh Đào Ngâm Mật Ong', category: 'Hô hấp', ingredients: ['Chanh đào', 'Mật ong nguyên chất', 'Đường phèn'],
    benefits: 'Bài thuốc chuẩn nhất trị ho khan, ho có đờm, viêm họng hạt, tăng cường sức đề kháng và bảo vệ hô hấp.',
    keywords: ['ho khan', 'ho có đờm', 'viêm họng', 'đau họng', 'chuẩn nhất', 'đề kháng', 'hô hấp'],
    usage: 'Mỗi sáng pha 1-2 thìa cốt chanh đào mật ong với nước ấm, uống khi bụng đói.', image: '🍋',
    steps: ['Chanh đào rửa sạch ngâm nước muối loãng, vớt ra để thật khô ráo rồi thái lát mỏng.', 'Chuẩn bị hũ thủy tinh sạch, xếp một lớp đường phèn dưới đáy, rồi đến một lớp chanh đào.', 'Tiếp tục xếp xen kẽ đến khi gần đầy hũ.', 'Đổ mật ong nguyên chất ngập mặt chanh, đậy kín nắp và bảo quản nơi thoáng mát. Sau 1 tháng là dùng được.'],
    imageUrl: '/images/chanh_dao_mat_ong.jpg' }
];
